apiVersion: v1 #Kubernetes API version
kind: Service #Kubernetes resource kind we are creating
metadata: #Metadata of the resource kind we are creating
   name: lms-kubernetes-service
spec:
  selector:
     app: lms-docker-kubernetes  # deployment selector
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: NodePort
 
     